#include "ClarityCore.h"
#include "tSystem\tString.Def.h"

::CLRVM::TValValue< ::CLRX::NtSystem::tBoolean >::Type CLRX::NtSystem::tString::mcode_stEquals(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tBoolean >::Type CLRX::NtSystem::tString::mcode_stop__Equality(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tBoolean >::Type CLRX::NtSystem::tString::mcode_stop__Inequality(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type CLRX::NtSystem::tString::mcode_itget__Chars(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type CLRX::NtSystem::tString::mcode_itToCharArray(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type CLRX::NtSystem::tString::mcode_itToCharArray(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itget__Length(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tString > >::Type CLRX::NtSystem::tString::mcode_itSplit(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tString > >::Type CLRX::NtSystem::tString::mcode_itSplit(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itSubstring(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itSubstring(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itTrim(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itTrimStart(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itTrimEnd(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
void CLRX::NtSystem::tString::mcode_it_d_ctor(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param2) { CLARITY_NOTIMPLEMENTED; }
void CLRX::NtSystem::tString::mcode_it_d_ctor(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
void CLRX::NtSystem::tString::mcode_it_d_ctor(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_stCompare(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itCompareTo(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tObject >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itCompareTo(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param2) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOfAny(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOfAny(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOfAny(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param2) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param2) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tChar >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param2) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOfAny(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOfAny(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOfAny(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tChar > >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param2) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type CLRX::NtSystem::tString::mcode_itLastIndexOf(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tInt32 >::Type param2) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itToLower(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itToUpper(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_itTrim(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type bThis0) { CLARITY_NOTIMPLEMENTED; }

::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_stConcat(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param1) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_stConcat(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param2) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_stConcat(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param0, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param1, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param2, ::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type param3) { CLARITY_NOTIMPLEMENTED; }
::CLRVM::TValValue< ::CLRX::NtSystem::tString >::Type CLRX::NtSystem::tString::mcode_stConcat(const ::CLRExec::Frame &frame, ::CLRVM::TValValue< ::CLRCore::SZArray< ::CLRX::NtSystem::tString > >::Type param0) { CLARITY_NOTIMPLEMENTED; }
